- name: Directories are present
  file:
    path="{{ item }}"
    state=directory
    mode=0777
  with_items: "{{ directories }}"
  tags: [jenkins]

- name: Container is running
  docker_container:
    name=jenkins
    image=ghcr.io/udloficial/jenkins:main
    ports=8080:8080
    volumes=/data/jenkins:/var/jenkins_home
  tags: [jenkins]
