- name: Latest container is pulled
  shell: sudo docker pull ghcr.io/udloficial/sakai:main
  tags: [sakai-service]

- name: Container is absent
  docker_container:
    image=ghcr.io/udloficial/sakai:main
    name=sakai-service
    state=absent
  tags: [sakai-service]

- name: Container is running
  docker_container:
    name=sakai-service
    image=ghcr.io/udloficial/sakai:main
    ports=9001:8080
    state=started
  tags: [sakai-service]
